//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackgroundWorker.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/plusplus", ReplyAction="http://tempuri.org/IService/plusplusResponse")]
        int plusplus(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/addUser", ReplyAction="http://tempuri.org/IService/addUserResponse")]
        bool addUser(int changed, string PushNotificationUri, int delete, int UsePushNotifications, string UniqueID, string ImmoscoutURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateUri", ReplyAction="http://tempuri.org/IService/updateUriResponse")]
        int updateUri(int changed, string UniqueID, string PushNotificationUri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendToast", ReplyAction="http://tempuri.org/IService/SendToastResponse")]
        void SendToast(string title, string message, string PushNotificationUri);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : BackgroundWorker.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<BackgroundWorker.ServiceReference1.IService>, BackgroundWorker.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int plusplus(int v1, int v2) {
            return base.Channel.plusplus(v1, v2);
        }
        
        public bool addUser(int changed, string PushNotificationUri, int delete, int UsePushNotifications, string UniqueID, string ImmoscoutURL) {
            return base.Channel.addUser(changed, PushNotificationUri, delete, UsePushNotifications, UniqueID, ImmoscoutURL);
        }
        
        public int updateUri(int changed, string UniqueID, string PushNotificationUri) {
            return base.Channel.updateUri(changed, UniqueID, PushNotificationUri);
        }
        
        public void SendToast(string title, string message, string PushNotificationUri) {
            base.Channel.SendToast(title, message, PushNotificationUri);
        }
    }
}
